[workspace]
members = [ "config", "ghost","kdr", "loader"]
target.'cfg(target_arch = "wasm32")'.members = ["rest-api-server"]

[workspace.package]
authors = ["Lê Hàn Minh Khang (Khang Le) <mkhangle20@gmail.com>"]
version = "0.1.0"
edition = "2024"
