[workspace]
members = ["config", "ghost", "kdr", "loader", "puppeteer", "puppeteer-ws-mock-server", "rest-api-server", "spr"]

[workspace.package]
authors = ["Lê Hàn Minh Khang (Khang Le) <mkhangle20@gmail.com>"]
version = "0.1.0"
edition = "2024"
