[build]
# target = "x86_64-unknown-linux-gnu"
# target = "x86_64-pc-windows-gnu"
# target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']