[package]
name = "puppeteer-ws-mock-server"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
puppeteer = { path = "../puppeteer" }

actix-web = "4.10.2"
actix-ws = "0.3.0"
futures-util = "0.3.31"
tokio = { version = "1.44.2", features = ["macros"] }
